// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTaskManager.Data.Context;

namespace WebApiTaskManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            ID = 21,
                            Name = "Rados",
                            ProjectID = 11,
                            Surname = "Perovic"
                        },
                        new
                        {
                            ID = 22,
                            Name = "Marko",
                            ProjectID = 12,
                            Surname = "Nikolic"
                        },
                        new
                        {
                            ID = 23,
                            Name = "Nikola",
                            ProjectID = 13,
                            Surname = "Stefanovic"
                        },
                        new
                        {
                            ID = 24,
                            Name = "Milica",
                            ProjectID = 14,
                            Surname = "Spasic2"
                        },
                        new
                        {
                            ID = 25,
                            Name = "Rados2",
                            ProjectID = 11,
                            Surname = "Perovic2"
                        },
                        new
                        {
                            ID = 26,
                            Name = "Marko2",
                            ProjectID = 12,
                            Surname = "Nikolic2"
                        },
                        new
                        {
                            ID = 27,
                            Name = "Nikola2",
                            ProjectID = 13,
                            Surname = "Stefanovic2"
                        },
                        new
                        {
                            ID = 28,
                            Name = "Milica2",
                            ProjectID = 14,
                            Surname = "Spasic2"
                        });
                });

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 11,
                            Description = "Ovo je projekat iz EF Code first",
                            Name = "WebApi"
                        },
                        new
                        {
                            ID = 12,
                            Description = "Ovo je projekat iz EF Code first",
                            Name = "InformationSystem"
                        },
                        new
                        {
                            ID = 13,
                            Description = "Ovo je projekat iz EF Code first",
                            Name = "ERP"
                        },
                        new
                        {
                            ID = 14,
                            Description = "Ovo je projekat iz EF Code first",
                            Name = "CMS"
                        });
                });

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeEstimation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Member", b =>
                {
                    b.HasOne("WebApiTaskManager.Domain.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Task", b =>
                {
                    b.HasOne("WebApiTaskManager.Domain.Models.Member", "Member")
                        .WithMany("Tasks")
                        .HasForeignKey("MemberID");

                    b.HasOne("WebApiTaskManager.Domain.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Member", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WebApiTaskManager.Domain.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
